package it.prova.autonoleggio.model;

public enum Localita {
	// Rome
	ROMA_FIUMICINO_AEROPORTO, ROMA_CIAMPINO_AEROPORTO, ROMA_TERMINI_STAZIONE, ROMA_TIBURTINA_STAZIONE,

	// Milan
	MILANO_MALPENSA_AEROPORTO, MILANO_LINATE_AEROPORTO, MILANO_CENTRALE_STAZIONE,

	// Naples
	NAPOLI_CAPODICHINO_AEROPORTO, NAPOLI_CENTRALE_STAZIONE,

	// Turin
	TORINO_CASSELLE_AEROPORTO, TORINO_PORTA_NUOVA_STAZIONE, TORINO_PORTA_SUSA_STAZIONE,

	// Palermo
	PALERMO_PUNTA_RAISI_AEROPORTO, PALERMO_CENTRALE_STAZIONE,

	// Genoa
	GENOVA_SESTRI_AEROPORTO, GENOVA_PIAZZA_PRINCIPE_STAZIONE, GENOVA_BRIGNOLE_STAZIONE,

	// Bologna
	BOLOGNA_GUGLIELMO_MARCONI_AEROPORTO, BOLOGNA_CENTRALE_STAZIONE,

	// Florence
	FIRENZE_PERETOLA_AEROPORTO, FIRENZE_SANTA_MARIA_NOVELLA_STAZIONE,

	// Venice
	VENEZIA_MARCO_POLO_AEROPORTO, VENEZIA_SANTA_LUCIA_STAZIONE, VENEZIA_MESTRE_STAZIONE,

	// Verona
	VERONA_VILLAFRANCA_AEROPORTO, VERONA_PORTA_NUOVA_STAZIONE,

	// Additional locations
	PISA_GALILEI_AEROPORTO, PISA_CENTRALE_STAZIONE, CAGLIARI_ELMAS_AEROPORTO, CAGLIARI_CENTRALE_STAZIONE,
	BARI_KAROL_WOJTYLA_AEROPORTO, BARI_CENTRALE_STAZIONE
}
